# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSAssignmentSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSAssignmentSwiftUI
	pod 'SDWebImageSwiftUI'


  target 'iOSAssignmentSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSAssignmentSwiftUIUITests' do
    # Pods for testing
  end

end
